### ISSUE TITLE
voice recorder doesn't work in Android 13

### ISSUE THREAD

**Issue by Alireza-kzt** [anokabb/chat_composer#5]
After upgrading the operating system to Android 13, the voice recorder has a problem.

I/flutter ( 5707): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): │ #0   FlutterSoundRecorder.stopRecorder (package:flutter_sound_lite/public/flutter_sound_recorder.dart:787:13)
I/flutter ( 5707): │ #1   RecordAudioCubit.startRecord (package:impo_full/core/app/custom_packages/chat_composer/lib/cubit/recordaudio_cubit.dart:49:19)
I/flutter ( 5707): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5707): │ 🐛 FS:---> stopRecorder 
I/flutter ( 5707): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): │ #0   FlutterSoundRecorder._stopRecorder (package:flutter_sound_lite/public/flutter_sound_recorder.dart:797:13)
I/flutter ( 5707): │ #1   FlutterSoundRecorder.stopRecorder.<anonymous closure> (package:flutter_sound_lite/public/flutter_sound_recorder.dart:790:17)
I/flutter ( 5707): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5707): │ 🐛 FS:---> _stopRecorder 
I/flutter ( 5707): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): │ #0   FlutterSoundRecorder._stop (package:flutter_sound_lite/public/flutter_sound_recorder.dart:755:13)
I/flutter ( 5707): │ #1   FlutterSoundRecorder._stopRecorder (package:flutter_sound_lite/public/flutter_sound_recorder.dart:809:17)
I/flutter ( 5707): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5707): │ 🐛 FS:---> _stop
I/flutter ( 5707): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): │ #0   FlutterSoundRecorder.stopRecorderCompleted (package:flutter_sound_lite/public/flutter_sound_recorder.dart:265:13)
I/flutter ( 5707): │ #1   MethodChannelFlutterSoundRecorder.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_recorder.dart:80:22)
I/flutter ( 5707): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5707): │ 🐛 ---> stopRecorderCompleted: true
I/flutter ( 5707): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): │ #0   FlutterSoundRecorder.stopRecorderCompleted (package:flutter_sound_lite/public/flutter_sound_recorder.dart:277:13)
I/flutter ( 5707): │ #1   MethodChannelFlutterSoundRecorder.channelMethodCallHandler (package:flutter_sound_platform_interface/method_channel_flutter_sound_recorder.dart:80:22)
I/flutter ( 5707): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5707): │ 🐛 <---- stopRecorderCompleted: true
I/flutter ( 5707): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): │ #0   FlutterSoundRecorder._stop (package:flutter_sound_lite/public/flutter_sound_recorder.dart:768:13)
I/flutter ( 5707): │ #1   <asynchronous suspension>
I/flutter ( 5707): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5707): │ 🐛 FS:<--- _stop
I/flutter ( 5707): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): │ #0   FlutterSoundRecorder._stopRecorder (package:flutter_sound_lite/public/flutter_sound_recorder.dart:840:13)
I/flutter ( 5707): │ #1   <asynchronous suspension>
I/flutter ( 5707): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5707): │ 🐛 FS:<--- _stopRecorder : 
I/flutter ( 5707): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 5707): │ #0   FlutterSoundRecorder.stopRecorder (package:flutter_sound_lite/public/flutter_sound_recorder.dart:792:13)
I/flutter ( 5707): │ #1   <asynchronous suspension>
I/flutter ( 5707): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 5707): │ 🐛 FS:<--- stopRecorder 
I/flutter ( 5707): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/ViewRootImpl@c8b07af[MainActivity]( 5707): MSG_WINDOW_FOCUS_CHANGED 0 0
I/ViewRootImpl@c8b07af[MainActivity]( 5707): stopped(false) old = false
[log] [chat_composer] 🔴 Denied permissions

**Comment by A7MeDG0L0L** [comment]
Change targetSdkVersion to 32
